# Generated by Django 5.2.1 on 2025-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
