# Generated by Django 5.2.1 on 2025-05-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='created_at',
            new_name='sale_date',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='sale_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.order'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product'),
        ),
    ]
